name: "Setup"

runs:
  using: "composite"
  steps:
    - name: Set VOLTA_FEATURE_PNPM
      shell: bash
      run: export VOLTA_FEATURE_PNPM=1
    - uses: volta-cli/action@v4
    - name: Install Package Manager
      shell: bash
      run: |
        volta install node
        volta install corepack
        corepack enable
    - name: Install dependencies
      shell: bash
      run: |
        pnpm install
    - name: Generate files
      run: pnpm run gen
      shell: bash
