// Generated by Wrangler on Sat Jun 29 2024 00:06:14 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	TANZAKU_STATUS: KVNamespace;
	TOKEN_KEY: string;
	SALT: string;
	CHUO_TANZAK: D1Database;
}
