// Generated by Wrangler on Fri Jun 28 2024 12:09:53 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	TANZAKU_STATUS: KVNamespace;
	TOKEN_KEY: string;
	SALT: string;
	CHUO_TANZAK: D1Database;
}
